[versions]
agp = "8.1.1"
dokka-gradle-plugin = "1.8.20"
kotlin = "1.9.0"

[libraries]
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka-gradle-plugin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokkaLibrary = { id = "org.jetbrains.dokka", version = "1.8.20" }

